FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests -B

FROM eclipse-temurin:17-jre

WORKDIR /app

RUN addgroup --system hireconnect && adduser --system --ingroup hireconnect hireconnect

# Create upload directories
RUN mkdir -p /app/uploads/resumes

# Give permissions
RUN chown -R hireconnect:hireconnect /app/uploads

USER hireconnect

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8082

ENTRYPOINT ["java","-Xms128m","-Xmx256m","-Djava.security.egd=file:/dev/./urandom","-jar","app.jar"]
